apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restrict-container-security.yaml
  - require-resources.yaml
  - restrict-image-source.yaml
  - verify-image-signatures.yaml
