apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: workloads
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: workloads/demo-api
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  {{- include "platform.syncPolicy" . | nindent 2 }}
