apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: platform
  sources:
    - repoURL: https://kyverno.github.io/kyverno
      chart: kyverno
      targetRevision: {{ .Values.charts.kyverno }}
      helm:
        valueFiles: [$repo/platform/kyverno/values.yaml]
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.revision }}
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  {{- include "platform.syncPolicy" . | nindent 2 }}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
